server:
  port: 7500

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kmall_pms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

  cloud:
    # Alibaba Nacos Service Discovery
    nacos:
      discovery:
        server-addr: localhost:8848
    # Alibaba Sentinel
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080
  application:
    name: kmall-product

  # Thymeleaf Config
  thymeleaf:
    cache: false
  #Redis
  redis:
    host: 172.17.0.1
    port: 6379
  # Spring Session
  session:
    store-type: redis
    timeout: 30m
    redis:
      flush-mode: on_save
      namespace: spring:session
  # Spring Cache
  cache:
    type: redis
    redis:
      time-to-live: 360000
      use-key-prefix: true
      # Prevent chuan tou
      cache-null-values: true

  # Date Time Format
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

  # Zipkin Trace Visible
  zipkin:
    base-url: 'http://172.17.0.1:9411'
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1

#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      # 主键自增策略
      id-type: AUTO


kmall.thread:
  idle: 50
  maxSize: 200
  keepAlive: 20

logging:
  level:
    xyz.klenkiven: error
