server:
  port: 7700

spring:
  cloud:
    # Alibaba Nacos Service Discovery
    nacos:
      discovery:
        server-addr: localhost:8848
    # Alibaba Sentinel
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080
  application:
    name: kmall-third-party

# Alibaba Cloud OSS
alibaba:
  cloud:
    access-key: ***************************
    secret-key: ***************************
    oss:
      endpoint: oss-cn-beijing.aliyuncs.com
      bucket: klenkiven-kmall