server:
  port: 7700

spring:
  # Alibaba Nacos Service Discovery
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  application:
    name: kmall-third-party

# Alibaba Cloud OSS
alibaba:
  cloud:
    access-key: ***************************
    secret-key: ***************************
    oss:
      endpoint: oss-cn-beijing.aliyuncs.com
      bucket: klenkiven-kmall