server:
  port: 7700

spring:
  # Alibaba Nacos Service Discovery
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  application:
    name: kmall-third-party

# Alibaba Cloud OSS
alibaba:
  cloud:
    access-key: LTAI5t8Yi7QZ5qn5cM3t8ASK
    secret-key: rDacG3qBx2k6vTdPYTKXwGE8OA7K3V
    oss:
      endpoint: oss-cn-beijing.aliyuncs.com
      bucket: klenkiven-kmall
    sms:
      host: 'https://gyytz.market.alicloudapi.com'
      path: '/sms/smsSend'
      method: 'POST'
      appcode: '4a8735c0203f49178abaeacbfbeab976'
      smsSignId: '2e65b1bb3d054466b82f0c9d125465e2'
      templateId: '908e94ccf08b4476ba6c876d13f084ad'