spring:
  cloud:
    # Alibaba Nacos
    nacos:
      server-addr: 172.17.0.1:8848

    # Alibaba Sentinel
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080

  # Thymeleaf
  thymeleaf:
    cache: false

  # Zipkin Trace Visible
  zipkin:
    base-url: 'http://172.17.0.1:9411'
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1

  # Spring Session with Redis
  redis:
    host: 172.17.0.1
    port: 6379
  session:
    store-type: redis
    timeout: 30m
    redis:
      flush-mode: on_save
      namespace: spring:session

  # RabbitMQ
  rabbitmq:
    host: 172.17.0.1
    port: 5672
    virtual-host: /kmall
    username: guest
    password: guest
    listener:
      simple:
        acknowledge-mode: manual
management:
  endpoints:
    web:
      exposure:
        include: '*'
