server:
  port: 7400

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kmall_oms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

  # Alibaba Nacos Service Discovery
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  application:
    name: kmall-order

  # RabbitMQ
  rabbitmq:
    host: 172.17.0.1
    port: 5672
    virtual-host: /
    username: guest
    password: guest

  # Thymeleaf
  thymeleaf:
    cache: false

  # Spring Session with Redis
  redis:
    host: 172.17.0.1
    port: 6379
  session:
    store-type: redis
    timeout: 30m
    redis:
      flush-mode: on_save
      namespace: spring:session

#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      # 主键自增策略
      id-type: AUTO

# Kmall Thread Pool
kmall.thread:
  idle: 50
  maxSize: 200
  keepAlive: 20