spring:
  cloud:
    gateway:
      routes:
        - id: baidu_test
          uri: https://www.baidu.com
          predicates:
            - Query=url,baidu

        - id: qq_test
          uri: https://www.qq.com
          predicates:
            - Query=url,qq

        # 酷商城-商品服务路由
        - id: kmall_product
          uri: lb://kmall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        # 酷商城-后台管理系统：前后端对接规则 /api/**
        - id: kmall_admin
          uri: lb://kmall-admin
          predicates:
            - Path=/api/**
          # 路由拦截器，例如访问某个位置
          # http://localhost:88/api/admin/role/list
          #                       | Gateway路由
          #                       V
          # http://localhost:7100/api/admin/role/list
          # 上面的访问方式并不能正常访问, 利用下面的过滤器，就可以截取合适的部分发送到指定服务位置
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}