server:
  port: 7200

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kmall_sms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

  cloud:
    # Alibaba Nacos Service Discovery
    nacos:
      discovery:
        server-addr: localhost:8848
    # Alibaba Sentinel
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080
  application:
    name: kmall-coupon

#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      # 主键自增策略
      id-type: AUTO

