server:
  port: 7600

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kmall_wms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

  cloud:
    # Alibaba Nacos Service Discovery
    nacos:
      discovery:
        server-addr: localhost:8848
    # Alibaba Sentinel
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080
  application:
    name: kmall-ware
  jackson:
    date-format: yyyy-MM-dd HH:mm

  # RabbitMQ
  rabbitmq:
    host: 172.17.0.1
    port: 5672
    virtual-host: /kmall
    username: guest
    password: guest
    listener:
      simple:
        acknowledge-mode: manual

#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      # 主键自增策略
      id-type: AUTO
logging:
  level:
    xyz.klenkiven: debug

# Seata Config
#seata:
#  enabled: true
#  tx-service-group: kmall_order_group
#  enable-auto-data-source-proxy: true
#  service:
#    vgroup-mapping:
#      kmall_order_group: default
#    grouplist:
#      default: localhost:8091
#    enable-degrade: false
#    disable-global-transaction: false
#  config:
#    type: nacos
#    nacos:
#      group: SEATA_GROUP
#      server-addr: localhost:8848
#      username:
#      password:
#      namespace: 8c64375f-60ad-4d54-b793-dbf9df64f849
#  registry:
#    type: nacos
#    nacos:
#      application: seata-server
#      server-addr: localhost:8848
#      group: SEATA_GROUP
#      namespace: 8c64375f-60ad-4d54-b793-dbf9df64f849
#      username:
#      password:
#      cluster: default
