spring:
  thymeleaf:
    cache: false
  #Redis
  redis:
    host: 172.17.0.1
    port: 6379

  # Spring Session
  session:
    store-type: redis
    timeout: 30m
    redis:
      flush-mode: on_save
      namespace: spring:session