server:
  port: 7800

spring:
  cloud:
    # Alibaba Nacos Service Discovery
    nacos:
      discovery:
        server-addr: localhost:8848
    # Alibaba Sentinel
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080
  application:
    name: kmall-search
  #Redis
  redis:
    host: 172.17.0.1
    port: 6379
  # Spring Session
  session:
    store-type: redis
    timeout: 30m
    redis:
      flush-mode: on_save
      namespace: spring:session

  thymeleaf:
    cache: false
