spring:
  cloud:
    # Alibaba Nacos Service Discovery
    nacos:
      discovery:
        server-addr: localhost:8848
    # Alibaba Sentinel
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080

  thymeleaf:
    cache: false
  #Redis
  redis:
    host: 172.17.0.1
    port: 6379
  session:
    store-type: redis

# Kmall Thread Pool
kmall.thread:
  idle: 50
  maxSize: 200
  keepAlive: 20