spring:
  thymeleaf:
    cache: false
  #Redis
  redis:
    host: 172.17.0.1
    port: 6379
  session:
    store-type: redis

# Kmall Thread Pool
kmall.thread:
  idle: 50
  maxSize: 200
  keepAlive: 20